port: 5000
externalUrl: http://localhost:5000
trustProxy: false
# listen on 0.0.0.0 instead of 127.0.0.1
# should be `true` for Docker deployment
expose: true

jwt:
    secret: E/=_r+a]H'8wHG](99"9'^X?K~+U\#]Gmged
    expiresIn: 1d

log:
    console: true
    file: logs/main.log

mongo:
    uri: mongodb://mongo:27017/main
