version: '3'
services:
    app:
        build: .
        restart: always
        ports:
            - '5000:5000'
        depends_on:
            - mongo

    mongo:
        image: mongo:latest
        ports:
            - '27017:27017'
        volumes:
            - mongo_data:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT_PASSWORD:-root}
            MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-password}

volumes:
    mongo_data:
