version: '3'
services:
    app:
        build: .
        restart: always
        ports:
            - '5000:5000'
        depends_on:
            - db
            - redis

    db:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root-password}
            MYSQL_DATABASE: ${DB_NAME:-main}
            MYSQL_USER: ${DB_USER:-admin}
            MYSQL_PASSWORD: ${DB_PASSWORD:-password}
        ports:
            - '3306:3306'
        volumes:
            - mysql-data:/var/lib/mysql

    redis:
        image: redis:latest
        restart: always
        ports:
            - '6379:6379'
        volumes:
            - redis-data:/data

volumes:
    mysql-data:
    redis-data:
